# This workflow get the magento code base
name: 'EP CI/CD - MAGENTO CODE BASE S3 UPLOAD'
description: 'Download the magento code base from S3 using aws cli'
inputs:
  dest_dir:
    description: 'The destination directory'
    required: true
    default: 'test'

runs:
  using: "composite"
  steps:
    - run: echo donwload to.
      shell: bash
