name: "Test CI CD workflow"

on:
  push:
    branches: [ main-githubactions-test ]

jobs:
 hell_job:
  name: Hello CI CD Job
  runs-on: self-hosted
  steps:
    - run: echo "Hello Othmane Chtoune !!"
    - run: mkdir test
    - run: cd test
    - uses: actions/checkout@v2
